### ISSUE TITLE
[def get_blob] is faulty 

### ISSUE THREAD

**Issue by seychelles111** [cclgroupltd/ccl_chrome_indexeddb#20]
using Teams... 

````
    raise ValueError("Can't resolve blob if blob dir is not set")
ValueError: Can't resolve blob if blob dir is not set````



-------------------------------

c:/etc/etc/indexdb

**Comment by seychelles111** [comment]
channel-roster-version-store Teams:channel-info-pane-manager:fb37c808-6ca7-40eb-8746-85795efcbd36:8:orgid:246d6ad6-b7ca-477a-a94d-caa5a0b8ab42 (Records: 0)
infoPaneInternalDataStore Teams:channel-info-pane-manager:fb37c808-6ca7-40eb-8746-85795efcbd36:8:orgid:246d6ad6-b7ca-477a-a94d-caa5a0b8ab42 (Records: 0)
app-entitlements Teams:channel-installed-apps-manager:fb37c808-6ca7-40eb-8746-85795efcbd36:246d6ad6-b7ca-477a-a94d-caa5a0b8ab42 (Records: 0)
app-definitions Teams:channel-installed-apps-manager:fb37c808-6ca7-40eb-8746-85795efcbd36:246d6ad6-b7ca-477a-a94d-caa5a0b8ab42 (Records: 0)
app-entitlements Teams:chat-installed-apps-manager:fb37c808-6ca7-40eb-8746-85795efcbd36:246d6ad6-b7ca-477a-a94d-caa5a0b8ab42 (Records: 0)
app-definitions Teams:chat-installed-apps-manager:fb37c808-6ca7-40eb-8746-85795efcbd36:246d6ad6-b7ca-477a-a94d-caa5a0b8ab42 (Records: 0)
Traceback (most recent call last):
  File "C:\Users\anon\Documents\teams archive\forensicsim\tools\dump_leveldb.py", line 68, in <module>
    process_cmd()
  File "C:\Users\anon\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anon\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\anon\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anon\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anon\Documents\teams archive\forensicsim\tools\dump_leveldb.py", line 64, in process_cmd
    process_db(filepath, outputpath)
  File "C:\Users\anon\Documents\teams archive\forensicsim\tools\dump_leveldb.py", line 39, in process_db
    extracted_values = parse_db(input_path, do_not_filter=True)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anon\AppData\Local\Programs\Python\Python311\Lib\site-packages\forensicsim\backend.py", line 75, in parse_db
    extracted_values.append({
  File "C:\Users\anon\AppData\Local\Programs\Python\Python311\Lib\site-packages\chromedb\ccl_chromium_indexeddb.py", line 846, in iterate_records
    yield from self._raw_db.iterate_records(
  File "C:\Users\anon\AppData\Local\Programs\Python\Python311\Lib\site-packages\chromedb\ccl_chromium_indexeddb.py", line 641, in iterate_records
    precursor = self.read_record_precursor(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anon\AppData\Local\Programs\Python\Python311\Lib\site-packages\chromedb\ccl_chromium_indexeddb.py", line 600, in read_record_precursor
    blob = self.get_blob(db_id, store_id, key.raw_key, externally_serialized_blob_index).read()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anon\AppData\Local\Programs\Python\Python311\Lib\site-packages\chromedb\ccl_chromium_indexeddb.py", line 692, in get_blob
    raise ValueError("Can't resolve blob if blob dir is not set")
ValueError: Can't resolve blob if blob dir is not set
PS C:\Users\anon\Documents\teams archive\forensicsim>

**Comment by cclgroupltd** [comment]
Hi there,

This isn't an issue at our end that I can see - IndexedDB stores data (both record and external files) in both the leveldb and blob folders. If the blob folder isn't provided it can't access the blob folder. This probably needs to be addressed in the application using the library I think.
